language: python
jobs:
  include:
    # Docker: checkstyle and tests (without coverage)
    - name: "Docker"
      services:
        - docker
      install:
        - make build-docker
      script: # NOTE: needed to override the generic "script" section
        - make checkstyle-docker
        - make test-docker
      after_success: # NOTE: needed to override the generic "after_success" section (i.e. coveralls report)
        - docker ps -a
    # Linux: checkstyle and tests (with coverage)
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.8"
      python: 3.8
install:
  - make build
  - pip install coveralls
script:
  - make checkstyle
  - make test-coverage
after_success:
  - coveralls
