language: python
python:
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - pylint ninjauri.py
  - coverage run --source=. -m unittest
after_success:
  - coveralls
