name: ninjauri
base: core22
version: '2.0.1'
summary: A simple data retrieval tool for URIs
description: |
  NinjaUri is a simple data retrieval tool for URIs.

architectures:
  - build-on: amd64
    build-for: amd64

grade: stable
confinement: strict

parts:
  dependencies:
    plugin: python
    python-packages:
      - pipenv
    source: .
  ninjauri:
    after:
      - dependencies
    plugin: nil
    source: .
    override-build: |
      pipenv install --system --deploy
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av ninjauri.py $SNAPCRAFT_PART_INSTALL/bin/ninjauri.py

apps:
  ninjauri:
    command: usr/bin/python3 $SNAP/bin/ninjauri.py
    plugs:
      - network
